name: Python Script workflow

on:
    workflow_dispatch:

jobs:
    run-python-script:
        runs-on: ubuntu-latest

        steps:
            - name: checkout branch
              uses: actions/checkout@v4
              
            - name: script workflow
              run: echo "Script workflow"

            - name: run python
              run: python script.py

